In [ ]:
print('Hello World!')

Hello World!


In [ ]:
import numpy as np

In [ ]:
np.__version__

'1.21.6'

In [ ]:
exams = np.asanyarray([[100,200,50,400],[50, 0, 0, 100],[350, 100, 50, 200]])

In [ ]:
print(exams)

[[100 200  50 400]
 [ 50   0   0 100]
 [350 100  50 200]]


In [ ]:
u_a=[100, 200, 50, 400]
u_b = [50, 0, 0, 100]
u_c = [350, 100, 50, 200]
exams = [u_a, u_b, u_c]

In [ ]:
print(exams)

[[100, 200, 50, 400], [50, 0, 0, 100], [350, 100, 50, 200]]


In [ ]:
my_list = [i for i in range(1000000)]

In [ ]:
my_array = np.arange(1000000)

In [ ]:
%time for _ in range(10): my_list2 = [x**2 for x in my_list]

CPU times: user 2.76 s, sys: 198 ms, total: 2.96 s
Wall time: 2.96 s


In [ ]:
%time for _ in range(10): my_array_2 = my_array **2

CPU times: user 20.4 ms, sys: 983 µs, total: 21.4 ms
Wall time: 34.6 ms


In [ ]:
print(my_array)

[     0      1      2 ... 999997 999998 999999]


In [ ]:
print(my_list)

IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)



In [ ]:
import numpy as np

In [ ]:
one_dim = np.array([1,2,3,4])
type(one_dim)

numpy.ndarray

In [ ]:
one_dim.shape

(4,)

In [ ]:
one_dim.ndim

1

In [ ]:
one_dim_horizontal = np.array([[1,2,3,4]])
print(one_dim_horizontal.shape)
one_dim_horizontal

(1, 4)


array([[1, 2, 3, 4]])

In [ ]:
one_dim_vertical = one_dim_horizontal.reshape(-1, 1)
one_dim_vertical

array([[1],
       [2],
       [3],
       [4]])

In [ ]:
one_dim_vertical.reshape(1, -1)

array([[1, 2, 3, 4]])

In [ ]:
two_dim = np.array([[100,200,50,400],[50, 0, 0, 100], [350, 100, 50,200]])
print("len: "+str(len(two_dim)))
print("shape: "+str(two_dim.shape))
print("ndim: "+str(two_dim.ndim))

len: 3
shape: (3, 4)
ndim: 2


In [ ]:
two_dim.size

12

In [ ]:
two_dim.itemsize

8

In [ ]:
one_dim

array([1, 2, 3, 4])

In [ ]:
one_dim.reshape(2,2)

array([[1, 2],
       [3, 4]])

In [ ]:
two_dim

array([[100, 200,  50, 400],
       [ 50,   0,   0, 100],
       [350, 100,  50, 200]])

In [ ]:
two_dim.reshape(4,3)

array([[100, 200,  50],
       [400,  50,   0],
       [  0, 100, 350],
       [100,  50, 200]])

In [ ]:
two_dim.flatten()

array([100, 200,  50, 400,  50,   0,   0, 100, 350, 100,  50, 200])

In [ ]:
two_dim.transpose()

array([[100,  50, 350],
       [200,   0, 100],
       [ 50,   0,  50],
       [400, 100, 200]])

In [ ]:
my_list = [1,2,3,4,5]
np.array(my_list)

array([1, 2, 3, 4, 5])

In [ ]:
my_nested_list = [[1,2,3],[4,5,6],[7,8,9]]
np.array(my_nested_list)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
np.arange(0,20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
np.zeros(3)

array([0., 0., 0.])

In [ ]:
np.zeros((5,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [ ]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
np.ones((2,3), dtype=np.int8)

array([[1, 1, 1],
       [1, 1, 1]], dtype=int8)

In [ ]:
arr_01 = np.array([5,10,20])
print(arr_01, arr_01.dtype)
arr_02 = np.array([5,10,20.0])
print(arr_02, arr_02.dtype)
arr_03 = np.array([5,10,"20"])
print(arr_03, arr_03.dtype)

[ 5 10 20] int64
[ 5. 10. 20.] float64
['5' '10' '20'] <U21


In [ ]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [ ]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
np.diag([5,0,4,1,3,2])

array([[5, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 4, 0, 0, 0],
       [0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 3, 0],
       [0, 0, 0, 0, 0, 2]])

In [ ]:
np.random.rand(5)

array([0.36930436, 0.84189979, 0.62920353, 0.52395349, 0.02433259])

In [ ]:
np.random.rand(5,5)

array([[0.60466244, 0.67969408, 0.28863669, 0.60694336, 0.54639856],
       [0.07295693, 0.70483582, 0.09365637, 0.02869296, 0.62896739],
       [0.39918684, 0.79482895, 0.2329905 , 0.93970957, 0.23966413],
       [0.71696192, 0.98369526, 0.45737837, 0.09863082, 0.70215227],
       [0.35580572, 0.84453922, 0.8168619 , 0.81199803, 0.98620072]])

In [ ]:
np.random.randint(1,100,10)

array([85, 81, 62, 97, 62,  8, 18, 64,  9, 48])

In [ ]:
np.linspace(0, 1, 10, endpoint= False)[1:]

array([0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

In [ ]:
macierz = np.array([[0,1,2,3,4]])
macierz = macierz.reshape(-1,1)
np.full((5, 5), macierz)

array([[0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3],
       [4, 4, 4, 4, 4]])