**Slicing i indexung**

In [ ]:
import numpy as np
my_arr = np.arange(21)
print(my_arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [ ]:
my_arr[10]

10

In [ ]:
my_arr[5:15]

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
my_arr[5:15:5]

array([ 5, 10])

In [ ]:
two_dim = np.array([[0,10,20], [5,15,25], [100, 200, 300]])
two_dim

array([[  0,  10,  20],
       [  5,  15,  25],
       [100, 200, 300]])

In [ ]:
two_dim[0]

array([ 0, 10, 20])

In [ ]:
two_dim[1][0]

5

In [ ]:
two_dim[1:3,:2]

array([[  5,  15],
       [100, 200]])

In [ ]:
my_arr = np.arange(25).reshape(5,5)
my_arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [ ]:
my_arr[(0,1)]

1

In [ ]:
my_arr[(0,1),]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [ ]:
my_arr[[0,1],[0,4]]

array([0, 9])

In [ ]:
vals =np.array([100,5,0])
select = np.random.randint(0,3, size=(4,3))
select

array([[0, 1, 2],
       [0, 0, 0],
       [2, 2, 2],
       [0, 0, 1]])

In [ ]:
vals[select]

array([[100,   5,   0],
       [100, 100, 100],
       [  0,   0,   0],
       [100, 100,   5]])

In [ ]:
vals[[1, 0, 2]]

array([  5, 100,   0])

**Views i copies**

In [ ]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
slice_of_arr = arr[:5]
slice_of_arr

array([0, 1, 2, 3, 4])

In [ ]:
slice_of_arr[:] = 100
slice_of_arr

array([100, 100, 100, 100, 100])

In [ ]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9])

In [ ]:
fancy_arr = np.arange(10)
fancy_arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
fancy_index_arr = fancy_arr[np.arange(5)]
fancy_index_arr

array([0, 1, 2, 3, 4])

In [ ]:
fancy_index_arr[:] = 100
fancy_index_arr

array([100, 100, 100, 100, 100])

In [ ]:
fancy_arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
slice_of_arr.base is None

False

In [ ]:
fancy_index_arr.base is None

True

In [ ]:
slice_of_arr.base is arr

True

In [ ]:
arr = np.arange(10)
print("arr")
print(arr)

arr
[0 1 2 3 4 5 6 7 8 9]


In [ ]:
slice_of_arr = arr[:5].copy()
print("slice_of_arr")
print(slice_of_arr)

slice_of_arr
[0 1 2 3 4]


In [ ]:
slice_of_arr[:] = 100
print("slice_of_arr")
print(slice_of_arr)

slice_of_arr
[100 100 100 100 100]


In [ ]:
print("arr")
print(arr)

arr
[0 1 2 3 4 5 6 7 8 9]


In [ ]:
slice_of_arr is arr

False

In [ ]:
macierz = np.arange(9).reshape(3,3)
print(macierz)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
macierz[-1,-1] = 999
print(macierz)
macierz[1:,1:] = 0
print('\n', macierz)

[[  0   1   2]
 [  3   4   5]
 [  6   7 999]]

 [[0 1 2]
 [3 0 0]
 [6 0 0]]


In [ ]:
razem = np.array([1,2,0,0,4,0])
razem

array([1, 2, 0, 0, 4, 0])

In [ ]:
np.nonzero(razem)

(array([0, 1, 4]),)

In [ ]:
np.transpose(np.nonzero(razem))

array([[0],
       [1],
       [4]])

**Masking**

In [ ]:
arr = np.arange(0,50,5)
arr

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [ ]:
arr>15

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [ ]:
arr[arr>15]

array([20, 25, 30, 35, 40, 45])

In [ ]:
arr[(arr>15)&(arr!=40)]

array([20, 25, 30, 35, 45])

In [ ]:
arr[(arr<10) | (arr>=20)]

array([ 0,  5, 20, 25, 30, 35, 40, 45])

In [ ]:
arr[np.logical_or(arr<10, arr>=20)]

array([ 0,  5, 20, 25, 30, 35, 40, 45])

In [ ]:
m = np.arange(0,30,2)
m

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [ ]:
m[(m<12)&(m>= 4)]

array([ 4,  6,  8, 10])

In [ ]:
m[(m>30)| (m>20)]

array([22, 24, 26, 28])

In [ ]:
m[(m>30)^(m>20)]

array([22, 24, 26, 28])

In [ ]:
m[~(m>20)&~(m<10)]

array([10, 12, 14, 16, 18, 20])

In [ ]:
np.where(arr<=43)

(array([0, 1, 2, 3, 4, 5, 6, 7, 8]),)

In [ ]:
print(arr)
(arr<10)|(arr>=20)&(arr!=40)

[ 0  5 10 15 20 25 30 35 40 45]


array([ True,  True, False, False,  True,  True,  True,  True, False,
        True])

In [ ]:
arr[((arr<10)|(arr>=20)&(arr!=40))]

array([ 0,  5, 20, 25, 30, 35, 45])

In [ ]:
np.logical_xor(0, np.eye(4))

array([[ True, False, False, False],
       [False,  True, False, False],
       [False, False,  True, False],
       [False, False, False,  True]])

**Mix - indexing, sclicing oraz masking**

In [ ]:
arr = np.arange(20).reshape(4,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [ ]:
arr[[3,0,1],:3]

array([[15, 16, 17],
       [ 0,  1,  2],
       [ 5,  6,  7]])

In [ ]:
arr.sum()

190

In [ ]:
arr[arr.sum(axis=1)>10,2:]

array([[ 7,  8,  9],
       [12, 13, 14],
       [17, 18, 19]])

**Ćwiczenie**

1. Zwróć z macierzy arr wiersz o indeksie nr 2, lecz tylko dla tych kolumn, których suma przekracza 30.

In [ ]:
arr[2,arr.sum(axis=0)>30]

array([11, 12, 13, 14])

2. Mamy dane dwie tablice: a i b. Stwórz program filtrujący wartości z b, które korespondują z elementami a i są większe od 100 i mniejsze od 110.
a = np.array([97,101,105,111,117,125])
b = np.array(['a','e','i','o','u','y'])

In [ ]:
a = np.array([97, 101, 105, 111, 117, 125])
a

array([ 97, 101, 105, 111, 117, 125])

In [ ]:
b = np.array(['a','e','i','o','u','y'])
b

array(['a', 'e', 'i', 'o', 'u', 'y'], dtype='<U1')

In [ ]:
a_a = np.where((a>100)&(a<110))
a_a

(array([1, 2]),)

In [ ]:
b_b = b[a_a]
b_b

array(['e', 'i'], dtype='<U1')

3. Stwórz program, który ze wskazanej macierzy wyciągnie odpowiednio najmniejszą i największą wartość dla każdego wiersza.

In [ ]:
m = np.array([[0,4,1],[2,0,4]])
m

array([[0, 4, 1],
       [2, 0, 4]])

In [ ]:
min = np.amin(m, axis=1)
min

array([0, 0])

In [ ]:
max = np.amax(m, axis=1)
max

array([4, 4])

4. Mając tablicę np.arange(11), odwróć znak wszystkich elementów większych od 3 i mniejszych od 8.

In [68]:
m = np.arange(11)
m

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [16]:
m_1=np.where((m>3)&(m<8))
m_1

(array([4, 5, 6, 7]),)

In [18]:
m_2 = m[m_1]
-m_2

array([-4, -5, -6, -7])

In [76]:
-(m[(m > 3)&(m < 8)])

array([-4, -5, -6, -7])

**Operacje na macierzach**

In [ ]:
import numpy as np
macierz_1 = np.array([[1,3,6],[7,1,1],[7,2,7]])
print(f'Macierz 1\n{macierz_1}')
macierz_2 = np.array([[-9,3,7],[7,3,1],[-1,-9,5]])
print(f'Macierz 2\n{macierz_2}')

Macierz 1
[[1 3 6]
 [7 1 1]
 [7 2 7]]
Macierz 2
[[-9  3  7]
 [ 7  3  1]
 [-1 -9  5]]


In [ ]:
macierz_1 + macierz_2

array([[-8,  6, 13],
       [14,  4,  2],
       [ 6, -7, 12]])

In [ ]:
np.add(macierz_1,macierz_2)

array([[-8,  6, 13],
       [14,  4,  2],
       [ 6, -7, 12]])

In [ ]:
macierz_1 - macierz_2

array([[10,  0, -1],
       [ 0, -2,  0],
       [ 8, 11,  2]])

In [ ]:
np.subtract(macierz_1, macierz_2)

array([[10,  0, -1],
       [ 0, -2,  0],
       [ 8, 11,  2]])

In [ ]:
print(macierz_1 * 10)
print()
print(macierz_1 * macierz_2)

[[10 30 60]
 [70 10 10]
 [70 20 70]]

[[ -9   9  42]
 [ 49   3   1]
 [ -7 -18  35]]


In [ ]:
macierz_1.dot(macierz_2)

array([[  6, -42,  40],
       [-57,  15,  55],
       [-56, -36,  86]])

In [ ]:
macierz_2.dot(macierz_1)

array([[ 61, -10,  -2],
       [ 35,  26,  52],
       [-29,  -2,  20]])

**Broadcasting**

In [ ]:
np.arange(4) + 5

array([5, 6, 7, 8])

In [ ]:
np.ones((3,4)) + np.arange(4)

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [ ]:
np.arange(3).reshape((3,1)) + np.arange(3)

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [ ]:
arr = np.arange(0,101,10)
arr

array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [ ]:
arr + arr

array([  0,  20,  40,  60,  80, 100, 120, 140, 160, 180, 200])

In [ ]:
arr * arr

array([    0,   100,   400,   900,  1600,  2500,  3600,  4900,  6400,
        8100, 10000])

In [ ]:
arr + 5

array([  5,  15,  25,  35,  45,  55,  65,  75,  85,  95, 105])

In [ ]:
arr / 5

array([ 0.,  2.,  4.,  6.,  8., 10., 12., 14., 16., 18., 20.])

In [ ]:
left_ = np.arange(10).reshape(5,2)
right_ = np.arange(5).reshape(5,1)
left_

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [ ]:
right_

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [ ]:
left_ * right_

array([[ 0,  0],
       [ 2,  3],
       [ 8, 10],
       [18, 21],
       [32, 36]])

**Statystyki opisowe**

In [ ]:
arr = np.arange(0,101,10)
print(arr)
np.sqrt(arr)

[  0  10  20  30  40  50  60  70  80  90 100]


array([ 0.        ,  3.16227766,  4.47213595,  5.47722558,  6.32455532,
        7.07106781,  7.74596669,  8.36660027,  8.94427191,  9.48683298,
       10.        ])

In [ ]:
np.sin(arr)

array([ 0.        , -0.54402111,  0.91294525, -0.98803162,  0.74511316,
       -0.26237485, -0.30481062,  0.77389068, -0.99388865,  0.89399666,
       -0.50636564])

In [ ]:
np.multiply(arr,2)

array([  0,  20,  40,  60,  80, 100, 120, 140, 160, 180, 200])

**Ćwiczenia**

1. Stwórz program, który ze wskazanej macierzy wyciągnie odpowiednio najmniejszą i największą wartość dla każdego wiersza.
[[0 4 1]
[2 0 4]]

In [ ]:
import numpy as np

In [ ]:
m = np.array([[0,4,1], [2,0,4]])
m

array([[0, 4, 1],
       [2, 0, 4]])

In [ ]:
min = np.amin(m, axis=1)
min

array([0, 0])

In [ ]:
max = np.amax(m, axis=1)
max

array([4, 4])

2. Stwórz wektor Z według następującego wzoru: np.random.uniform(0,1,10). Następnie znajdź element, który jest najbliższy wartości 0.5.

In [ ]:
v = np.random.uniform(0,1,10)
v

array([0.10617536, 0.53166004, 0.18333656, 0.65158806, 0.5624627 ,
       0.17486945, 0.92622828, 0.61814564, 0.87020076, 0.43964391])

In [36]:
a = np.abs(v-0.5)
a

array([0.39382464, 0.03166004, 0.31666344, 0.15158806, 0.0624627 ,
       0.32513055, 0.42622828, 0.11814564, 0.37020076, 0.06035609])

In [30]:
np.amin(a)

0.031660038575070826

3. Stwórz wektor zawierający 20 losowych wartości, a następnie zamień jego największą wartość na 0.

In [37]:
from numpy import random

In [50]:
m = np.random.random(20)
m

array([0.1130543 , 0.65039557, 0.02845548, 0.36708139, 0.96329821,
       0.01781233, 0.0932402 , 0.52165711, 0.46084434, 0.35207873,
       0.07539174, 0.74770123, 0.8864022 , 0.53633995, 0.75231808,
       0.46534785, 0.08151666, 0.26910082, 0.05895886, 0.56777012])

In [66]:
m[m == np.amax(m)] = 0
m

array([0.1130543 , 0.65039557, 0.02845548, 0.36708139, 0.        ,
       0.01781233, 0.0932402 , 0.52165711, 0.46084434, 0.35207873,
       0.07539174, 0.74770123, 0.        , 0.53633995, 0.75231808,
       0.46534785, 0.08151666, 0.26910082, 0.05895886, 0.56777012])

4. Znajdź części całkowite tablicy, wykorzystując przynajmniej dwa różne sposoby.
np.array([5, 0.0249139 , 0.11873564, 0., 0.72321586, 11308494, 0.29931472, 0.24439968, 0.61251754, 4])

In [120]:
m = np.array([5, 0.0249139, 0.11873564, 0., 0.72321586, 11308494, 0.29931472, 0.24439968, 0.61251754, 4], dtype=np.int_)
m

array([       5,        0,        0,        0,        0, 11308494,
              0,        0,        0,        4])

In [119]:
np.modf(m)

(array([0.        , 0.0249139 , 0.11873564, 0.        , 0.72321586,
        0.        , 0.29931472, 0.24439968, 0.61251754, 0.        ]),
 array([5.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
        0.0000000e+00, 1.1308494e+07, 0.0000000e+00, 0.0000000e+00,
        0.0000000e+00, 4.0000000e+00]))

**Agregowanie**

In [121]:
arr = np.arange(0,101,10)
arr

array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [122]:
arr.sum()

550

In [123]:
arr.mean()

50.0

In [124]:
arr.max()

100

In [128]:
arr_2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr_2d, '\n')
print(arr_2d.min(axis=0), '\n')
print(arr_2d.max(axis=0), '\n')
print(arr_2d.min(axis=1))

[[1 2 3]
 [4 5 6]
 [7 8 9]] 

[1 2 3] 

[7 8 9] 

[1 4 7]


In [130]:
np.median(arr_2d)

5.0

In [131]:
np.var(arr_2d)

6.666666666666667

In [132]:
np.std(arr_2d)

2.581988897471611

In [133]:
arr/arr

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

**Sortowanie**

In [134]:
arr = np.random.randint(1,40,10)
arr

array([29, 26, 39, 30,  3, 10, 27, 17,  2, 17])

In [135]:
np.sort(arr)

array([ 2,  3, 10, 17, 17, 26, 27, 29, 30, 39])

In [136]:
arr=np.sort(arr)
arr

array([ 2,  3, 10, 17, 17, 26, 27, 29, 30, 39])

In [137]:
arr = np.sort(arr)[::-1]
arr

array([39, 30, 29, 27, 26, 17, 17, 10,  3,  2])

In [138]:
arr.sort()
arr

array([ 2,  3, 10, 17, 17, 26, 27, 29, 30, 39])

In [140]:
arr2d = np.array([np.arange(1,6), np.arange(6,1,-1)]).reshape(5,2)
arr2d

array([[1, 2],
       [3, 4],
       [5, 6],
       [5, 4],
       [3, 2]])

In [141]:
np.sort(arr2d)

array([[1, 2],
       [3, 4],
       [5, 6],
       [4, 5],
       [2, 3]])

In [142]:
np.sort(arr2d, axis=0)

array([[1, 2],
       [3, 2],
       [3, 4],
       [5, 4],
       [5, 6]])

In [143]:
dt = np.dtype([('student','S10'),('exam1',int),('exam2',int)])
a = np.array([("StudentA", 89, 74),("Student B", 85, 56),("Student C", 93, 44),("Student D", 83, 92)],dtype=dt)
a

array([(b'StudentA', 89, 74), (b'Student B', 85, 56),
       (b'Student C', 93, 44), (b'Student D', 83, 92)],
      dtype=[('student', 'S10'), ('exam1', '<i8'), ('exam2', '<i8')])

In [144]:
np.sort(a, order='exam1')

array([(b'Student D', 83, 92), (b'Student B', 85, 56),
       (b'StudentA', 89, 74), (b'Student C', 93, 44)],
      dtype=[('student', 'S10'), ('exam1', '<i8'), ('exam2', '<i8')])

In [145]:
np.sort(a, order='exam2')

array([(b'Student C', 93, 44), (b'Student B', 85, 56),
       (b'StudentA', 89, 74), (b'Student D', 83, 92)],
      dtype=[('student', 'S10'), ('exam1', '<i8'), ('exam2', '<i8')])

In [146]:
np.sort(a, order='exam2')[-1][0]

b'Student D'

In [152]:
arr

array([29,  5, 32, 30,  5, 36, 32, 33, 29,  2])

In [153]:
np.argsort(arr)

array([9, 1, 4, 0, 8, 3, 2, 6, 7, 5])

In [156]:
np.sort(a, order='exam2')[::-1]

array([(b'Student D', 83, 92), (b'StudentA', 89, 74),
       (b'Student B', 85, 56), (b'Student C', 93, 44)],
      dtype=[('student', 'S10'), ('exam1', '<i8'), ('exam2', '<i8')])

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
